# Generated by Django 4.0.4 on 2022-08-17 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255, verbose_name='작성자')),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('thumbnail', models.CharField(max_length=255, null=True, verbose_name='섬네일')),
                ('likes', models.IntegerField(default=0, verbose_name='좋아요')),
                ('views', models.IntegerField(default=0, verbose_name='조회수')),
                ('deleted', models.BooleanField(default=False, verbose_name='삭제')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='게시글 생성날짜')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='게시글 수정날짜')),
                ('fk_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'verbose_name': '게시글 테이블',
                'db_table': 'post',
            },
        ),
    ]
