# Generated by Django 4.0.4 on 2022-08-17 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oauth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=12, verbose_name='제공자')),
                ('social_id', models.CharField(max_length=255, verbose_name='소셜 아이디')),
                ('disabled', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='생성날짜')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='최근 접속날짜')),
                ('fk_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'verbose_name': '유저 테이블',
                'db_table': 'oauth',
            },
        ),
    ]
