# Generated by Django 4.0.4 on 2022-08-17 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='이름')),
                ('nickname', models.CharField(max_length=255, unique=True, verbose_name='닉네임')),
                ('email', models.CharField(max_length=255, unique=True, verbose_name='이메일')),
                ('thumbnail', models.CharField(max_length=255, null=True, verbose_name='썸네일')),
                ('is_certified', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='생성날짜')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='최근 접속날짜')),
            ],
            options={
                'verbose_name': '유저 테이블',
                'db_table': 'user',
            },
        ),
    ]
