# Generated by Django 4.0.4 on 2022-08-17 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenter', models.CharField(max_length=255, verbose_name='작성자 닉네임')),
                ('content', models.TextField(verbose_name='내용')),
                ('has_replies', models.BooleanField(default=False, verbose_name='대댓글')),
                ('reply_to', models.PositiveBigIntegerField(default=None, null=True, verbose_name='대댓글id')),
                ('level', models.IntegerField(default=0, verbose_name='레벨')),
                ('likes', models.IntegerField(default=0, verbose_name='좋아요')),
                ('deleted', models.BooleanField(default=False, verbose_name='삭제')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='댓글 생성날짜')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='댓글 수정날짜')),
                ('fk_post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post', verbose_name='게시글')),
                ('fk_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='작성자')),
            ],
            options={
                'verbose_name': '댓글 테이블',
                'db_table': 'comment',
            },
        ),
    ]
